/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Thu Apr 26 18:09:35 2007
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-c"
 * "visual_gui.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_visual_gui_public_data[] = {'3', '0', '8', '1', '9',
                                                      'D', '3', '0', '0', 'D',
                                                      '0', '6', '0', '9', '2',
                                                      'A', '8', '6', '4', '8',
                                                      '8', '6', 'F', '7', '0',
                                                      'D', '0', '1', '0', '1',
                                                      '0', '1', '0', '5', '0',
                                                      '0', '0', '3', '8', '1',
                                                      '8', 'B', '0', '0', '3',
                                                      '0', '8', '1', '8', '7',
                                                      '0', '2', '8', '1', '8',
                                                      '1', '0', '0', 'C', '4',
                                                      '9', 'C', 'A', 'C', '3',
                                                      '4', 'E', 'D', '1', '3',
                                                      'A', '5', '2', '0', '6',
                                                      '5', '8', 'F', '6', 'F',
                                                      '8', 'E', '0', '1', '3',
                                                      '8', 'C', '4', '3', '1',
                                                      '5', 'B', '4', '3', '1',
                                                      '5', '2', '7', '7', 'E',
                                                      'D', '3', 'F', '7', 'D',
                                                      'A', 'E', '5', '3', '0',
                                                      '9', '9', 'D', 'B', '0',
                                                      '8', 'E', 'E', '5', '8',
                                                      '9', 'F', '8', '0', '4',
                                                      'D', '4', 'B', '9', '8',
                                                      '1', '3', '2', '6', 'A',
                                                      '5', '2', 'C', 'C', 'E',
                                                      '4', '3', '8', '2', 'E',
                                                      '9', 'F', '2', 'B', '4',
                                                      'D', '0', '8', '5', 'E',
                                                      'B', '9', '5', '0', 'C',
                                                      '7', 'A', 'B', '1', '2',
                                                      'E', 'D', 'E', '2', 'D',
                                                      '4', '1', '2', '9', '7',
                                                      '8', '2', '0', 'E', '6',
                                                      '3', '7', '7', 'A', '5',
                                                      'F', 'E', 'B', '5', '6',
                                                      '8', '9', 'D', '4', 'E',
                                                      '6', '0', '3', '2', 'F',
                                                      '6', '0', 'C', '4', '3',
                                                      '0', '7', '4', 'A', '0',
                                                      '4', 'C', '2', '6', 'A',
                                                      'B', '7', '2', 'F', '5',
                                                      '4', 'B', '5', '1', 'B',
                                                      'B', '4', '6', '0', '5',
                                                      '7', '8', '7', '8', '5',
                                                      'B', '1', '9', '9', '0',
                                                      '1', '4', '3', '1', '4',
                                                      'A', '6', '5', 'F', '0',
                                                      '9', '0', 'B', '6', '1',
                                                      'F', 'C', '2', '0', '1',
                                                      '6', '9', '4', '5', '3',
                                                      'B', '5', '8', 'F', 'C',
                                                      '8', 'B', 'A', '4', '3',
                                                      'E', '6', '7', '7', '6',
                                                      'E', 'B', '7', 'E', 'C',
                                                      'D', '3', '1', '7', '8',
                                                      'B', '5', '6', 'A', 'B',
                                                      '0', 'F', 'A', '0', '6',
                                                      'D', 'D', '6', '4', '9',
                                                      '6', '7', 'C', 'B', '1',
                                                      '4', '9', 'E', '5', '0',
                                                      '2', '0', '1', '1', '1'
                                                      , '\0'};

const char *__MCC_visual_gui_name_data = "visual_gui";

const char *__MCC_visual_gui_root_data = "";

const unsigned char __MCC_visual_gui_session_data[] = {'9', 'E', '4', '1',
                                                       '6', '6', '4', '0',
                                                       '9', '0', '3', 'E',
                                                       '2', '6', '1', '6',
                                                       'E', 'E', 'F', 'A',
                                                       '0', '5', '7', 'A',
                                                       '8', 'B', '5', '7',
                                                       '1', '8', '6', '2',
                                                       '0', 'E', '2', 'E',
                                                       'A', 'A', 'E', 'E',
                                                       '1', '0', 'F', '5',
                                                       '1', '7', 'C', '8',
                                                       'E', '2', '1', '9',
                                                       'B', 'C', '0', 'F',
                                                       '9', '0', '3', 'A',
                                                       '8', '8', 'C', 'A',
                                                       '5', '9', 'C', 'B',
                                                       '9', 'A', 'D', 'A',
                                                       'A', 'A', '9', '3',
                                                       '9', '6', '2', '3',
                                                       '9', '3', '5', '2',
                                                       '1', '5', '9', '5',
                                                       'C', '8', '7', '7',
                                                       '0', '7', '8', 'A',
                                                       '6', 'A', '0', 'C',
                                                       '6', 'E', 'D', '3',
                                                       '0', '8', 'B', '3',
                                                       '0', '3', '0', 'E',
                                                       '5', '9', '4', '1',
                                                       '5', 'E', '2', '1',
                                                       '5', '1', 'F', 'F',
                                                       'B', 'C', 'C', '5',
                                                       '4', 'B', 'E', '5',
                                                       '3', '3', '5', '0',
                                                       '3', 'D', 'F', '3',
                                                       '8', 'B', 'C', 'A',
                                                       '6', '6', 'F', '7',
                                                       '8', '1', '1', '8',
                                                       'D', 'C', '0', 'A',
                                                       'D', '4', 'A', 'A',
                                                       'F', '1', '8', 'D',
                                                       '9', '5', 'D', '0',
                                                       '4', '4', '7', '8',
                                                       '0', '4', '9', '9',
                                                       'A', '7', '5', 'A',
                                                       '5', '4', 'E', 'D',
                                                       '5', '4', 'F', 'C',
                                                       '3', 'A', '8', '5',
                                                       'D', '6', '5', '8',
                                                       '2', '6', '1', '0',
                                                       '2', '4', '2', '6',
                                                       '8', 'A', 'B', '0',
                                                       '6', '0', '4', '1',
                                                       'D', '0', '8', 'D',
                                                       '3', '3', '6', '4',
                                                       '2', '8', 'B', '1',
                                                       '1', 'F', 'E', 'E',
                                                       'F', '0', 'C', '6',
                                                       'D', '3', '4', '7',
                                                       '1', 'C', '2', '6',
                                                       'C', 'F', '9', '9',
                                                       '8', '9', '0', '9',
                                                       '4', 'C', '9', '1',
                                                       '1', 'E', '8', 'A'
                                                       , '\0'};

const char *__MCC_visual_gui_matlabpath_data[] = {"visual_gui/",
                                                  "toolbox/compiler/deploy/",
                                                  "MATLAB_SOURCE/",
                                                  "$TOOLBOXMATLABDIR/general/",
                                                  "$TOOLBOXMATLABDIR/ops/",
                                                  "$TOOLBOXMATLABDIR/lang/",
                                                  "$TOOLBOXMATLABDIR/elmat/",
                                                  "$TOOLBOXMATLABDIR/elfun/",
                                                  "$TOOLBOXMATLABDIR/specfun/",
                                                  "$TOOLBOXMATLABDIR/matfun/",
                                                  "$TOOLBOXMATLABDIR/datafun/",
                                                  "$TOOLBOXMATLABDIR/polyfun/",
                                                  "$TOOLBOXMATLABDIR/funfun/",
                                                  "$TOOLBOXMATLABDIR/sparfun/",
                                                  "$TOOLBOXMATLABDIR/scribe/",
                                                  "$TOOLBOXMATLABDIR/graph2d/",
                                                  "$TOOLBOXMATLABDIR/graph3d/",
                                                  "$TOOLBOXMATLABDIR/specgraph/",
                                                  "$TOOLBOXMATLABDIR/graphics/",
                                                  "$TOOLBOXMATLABDIR/uitools/",
                                                  "$TOOLBOXMATLABDIR/strfun/",
                                                  "$TOOLBOXMATLABDIR/imagesci/",
                                                  "$TOOLBOXMATLABDIR/iofun/",
                                                  "$TOOLBOXMATLABDIR/audiovideo/",
                                                  "$TOOLBOXMATLABDIR/timefun/",
                                                  "$TOOLBOXMATLABDIR/datatypes/",
                                                  "$TOOLBOXMATLABDIR/verctrl/",
                                                  "$TOOLBOXMATLABDIR/codetools/",
                                                  "$TOOLBOXMATLABDIR/helptools/",
                                                  "$TOOLBOXMATLABDIR/winfun/",
                                                  "$TOOLBOXMATLABDIR/demos/",
                                                  "toolbox/local/",
                                                  "toolbox/compiler/",
                                                  "toolbox/images/images/",
                                                  "toolbox/images/imuitools/",
                                                  "toolbox/images/iptutils/",
                                                  "toolbox/symbolic/"};
const int __MCC_visual_gui_matlabpath_data_count = 37;

const char *__MCC_visual_gui_classpath_data[] = { "" };
const int __MCC_visual_gui_classpath_data_count = 0;

const char *__MCC_visual_gui_mcr_application_options[] = { "" };
const int __MCC_visual_gui_mcr_application_option_count = 0;
const char *__MCC_visual_gui_mcr_runtime_options[] = { "" };
const int __MCC_visual_gui_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


